apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: hasan-test
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: hasan-test project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: ingress-nginx
            version: "4.1.0"
            repoUrl: https://kubernetes.github.io/ingress-nginx
            chart: ingress-nginx
            namespace: ingress-nginx
          - name: go-site
            version: "0.*.*"
            repoUrl: https://hasanaburayyan.github.io/helm-charts/
            chart: go-site
            namespace: go-site
#          - name: kube-prometheus
#            version: "39.1.0"
#            repoUrl: https://prometheus-community.github.io/helm-charts
#            chart: kube-prometheus-stack
#            namespace: monitoring
#          - name: thanos
#            version: "10.3.6"
#            repoUrl: https://charts.bitnami.com/bitnami
#            chart: thanos
#            namespace: monitoring

  template:
    metadata:
      name: '{{name}}'
      labels:
        app.name: '{{name}}'
    spec:
      project: hasan-test
      source:
        repoURL: '{{repoUrl}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true