apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neil-app
  namespace: neil
spec:
  project: default

  source:
    repoURL: https://github.com/hasanaburayyan/argo-playground.git
    targetRevision: HEAD
    path: neil
  destination:
    server: https://kubernetes.default.svc
    namespace: neil
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
        selfHeal: true
        prune: true